scss_files: '**/*.scss'

exclude: '**/_normalize.scss'

linters:
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
  NestingDepth:
    enabled: false
  PseudoElement:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false

  TrailingSemicolon:
    enabled: false
  VendorPrefix:
    enabled: false
